/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./../components/card.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    Settings: typeof import('./../components/settings.vue')['default']
    Welcome: typeof import('./../components/welcome.vue')['default']
  }
}
